version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: jpa-hibernate-db
    environment:
      POSTGRES_DB: jpa_hibernate_db
      POSTGRES_USER: jpauser
      POSTGRES_PASSWORD: jpapass
    ports:
      - "5432:5432"
    volumes:
      - jpa_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jpauser -d jpa_hibernate_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  jpa_pg_data:
